"""
Regenerate games/language/wordlist_data.py: common English words with their frequency and a clue.

    python scripts/build_wordlist.py

Needs internet access (Datamuse). Frequency is occurrences per million words. The output is
committed, so players never need to run this.
"""

import json
import math
import os
import random
import re
import urllib.request

LENGTHS = range(4, 11)
MIN_FREQ = 0.15
PER_BUCKET = 8          # words kept per length per half-log10 frequency bucket
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "games", "language", "wordlist_data.py")


def fetch(length: int) -> list[dict]:
    url = f"https://api.datamuse.com/words?sp={'?' * length}&md=df&max=1000"
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=20) as resp:
        return json.loads(resp.read().decode())


def parse(item: dict):
    """(word, frequency, clue) or None if the entry is unusable."""
    word = item.get("word", "").lower()
    if not word.isalpha() or not word.isascii() or not item.get("defs"):
        return None
    freq = next((float(t[2:]) for t in item.get("tags", []) if t.startswith("f:")), None)
    if freq is None or freq < MIN_FREQ:
        return None
    raw = item["defs"][0]
    clue = raw.split("\t", 1)[-1].strip()
    clue = re.sub(r"\s*\(.*?\)\s*", " ", clue).strip()          # drop bracketed asides
    if len(clue) < 8 or len(clue) > 90:
        return None
    if word[:4] in clue.lower():                                 # clue would give the word away
        return None
    return word, freq, clue[0].upper() + clue[1:]


def main():
    rng = random.Random(7)
    rows = []
    for length in LENGTHS:
        parsed = [p for p in map(parse, fetch(length)) if p]
        buckets: dict[int, list] = {}
        for word, freq, clue in parsed:
            buckets.setdefault(math.floor(math.log10(freq) * 2), []).append((word, freq, clue))
        for key in sorted(buckets, reverse=True):
            pick = buckets[key]
            rng.shuffle(pick)
            rows.extend(sorted(pick[:PER_BUCKET], key=lambda r: -r[1]))
        print(length, len(parsed), "usable ->", sum(1 for r in rows if len(r[0]) == length), "kept")

    lines = ['"""Generated by scripts/build_wordlist.py - do not edit by hand.',
             '',
             '(word, occurrences per million words, clue)"""',
             '',
             'WORDS: list[tuple[str, float, str]] = [']
    for word, freq, clue in rows:
        lines.append(f"    ({word!r}, {round(freq, 3)}, {clue!r}),")
    lines.append("]")
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", len(rows), "words to", os.path.normpath(OUT))


if __name__ == "__main__":
    main()
